export const Home = () => {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-blue-50">
       
        <div className="homehelp ,  slideover">
           Chat with us
        </div>
        <p className="text-lg text-gray-600 mb-8 max-w-xl text-center">
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you  
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you  
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you  
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you  
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
         we are glad to see you right here...
         get in touch with counselling who can make a difference in you 
        

        </p>
        
        <button className="px-6 py-3 bg-blue-600 text-white rounded-lg shadow-md hover:bg-blue-700">
          Contact Us
        </button>
      </div>
    );
  };
  